# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            KvnKnowles
tagline:          "It's Blogin' Time!"
url:              http://kvnknowles.github.io
paginate:         1
baseurl:          /
author:
  name:           Kevin KNowles
  url:            https://twitter.com/kvnknowles
  email:          knowles.kevin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kvnknowles/kvnknowles.github.io
